apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: s3sel-sample
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "2"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "10"
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: s3access
        image: yasuoo/s3sel-sample:1.0.1
